version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DB_NAME=equity_bharat
      - SECRET_KEY=your-very-secret-key
      - SECRET_KEY_EXPIRE=12h
    # Uncomment the following line if you want to use an environment file
    # env_file:
    #   - .env
